{
 "title": "XPING - LONAP",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targetpeer",
    "label": "Target",
    "query": {
     "query": "label_values(xping_peer_latency_per_flow,peer)"
    }
   },
   {
    "name": "sourcepeer",
    "label": "Source",
    "query": {
     "query": "label_values(xping_peer_latency_per_flow,local)"
    }
   }
  ]
 },
 "panels": [
  { "title": "From", "type": "text", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 }, "options": { "content": "${targetpeer}\n===" } },
  { "title": "To", "type": "text", "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 }, "options": { "content": "${sourcepeer}\n===\n" } },
  {
   "title": "Worst Loss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(peer) (xping_peer_loss_per_flow{local=\"$sourcepeer\", peer=\"$targetpeer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Flow Latency from $targetpeer to $sourcepeer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "xping_peer_latency_per_flow{peer=\"$targetpeer\", local=\"$sourcepeer\"}",
     "legendFormat": "{{peer}} - {{port}}"
    }
   ]
  },
  {
   "title": "Per Flow Loss from $targetpeer to $sourcepeer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xping_peer_loss_per_flow{peer=\"$targetpeer\", local=\"$sourcepeer\"}",
     "legendFormat": "{{peer}} - {{port}}"
    }
   ]
  }
 ]
}