{
 "title": "XPING Overview - LONAP",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Avg Flow Latency between all test points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avgSwitchPairLatency", "legendFormat": "{{local}} -> {{peer}} " }
   ]
  },
  {
   "title": "Current Avg Latency between Switches",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by(local, peer) (xping_peer_latency_per_flow)"
    }
   ]
  },
  {
   "title": "Worst Flow Loss between all test ports",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "maxSwitchPairLoss", "legendFormat": "{{local}} -> {{peer}}" }
   ]
  },
  {
   "title": "Cases where loss was detected",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "maxSwitchPairLoss > 0.01", "legendFormat": "__auto" }
   ]
  }
 ]
}